### PR TITLE
Update monaco-editor peerDependencies version

### PR DESCRIPTION
**Pull request by iamphill**
Updates the `monaco-editor` `peerDependencies` version to the `0.14.0` (latest minor version)

### CODE REVIEW

**Comment by NeekSandhu** [comment]
Thank you Phil!

**Comment by iamphill** [comment]
@NeekSandhu Would it be possible to get a new release on npm? 😃 

Currently integrating this into the GitLab Web IDE & we have a check in our CI for `peerDependencies` versions.

**Comment by NeekSandhu** [comment]
😳 How did I miss that!!!

Please update to `2.0.1` to get the patch!

PS: I might be brewing up a change to this package's backend/internals (public API __very unlikely to change__). Not sure on the ETA but less than 2 weeks for sure. So please check back then to see if that matters :) The change will have __nothing__ to do with performance or bugs, it'll just be "clean up"

**Comment by iamphill** [comment]
@NeekSandhu Nice! Thanks! 😄 

Thanks, i'll keep an eye on this package! 👍

**Pull request merged**
