### PR TITLE
Fix broken monaco API to get theme details

### PR DESCRIPTION
**Pull request by IamAfnanSk**
#19 
This issue is fixed in this PR.

### CODE REVIEW

**Comment by golmujik** [comment]
Hi Thank you its working fine now

**Comment by NeekSandhu** [comment]
This is a breaking change so we need to update the major version instead of just patch.

Also do not update the version manually in the package json. I'll do it myself through the `npm version` command.

You do not need to take any action I've fixed it up.

closes #16

**Comment by IamAfnanSk** [comment]
@NeekSandhu 👍🏼 better

**Comment by NeekSandhu** [comment]
`monaco-editor-textmate@3.0.0` is now live

**Pull request merged**
