### PR TITLE
Works with version 0.21.2 and up

### PR DESCRIPTION
**Pull request by tpisto**

### CODE REVIEW

**Comment by zikaari** [comment]
closes #16

**Comment by zikaari** [comment]
Is this backwards compatible or should I release it as a major version instead?

**Comment by tpisto** [comment]
Thank you for mergeing this. Previous pull request maker notified, that this works from 0.21.2 up. I think that maybe it's not backward compatibile. So please create new major release. Thank you!

**Comment by zikaari** [comment]
`monaco-editor-textmate@4.0.0` is now live. Thanks!

**Pull request merged**
